version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    image: nginx:latest
    tty: true
    ports:
      - 8081:8081
    links:
      - odoo1
      - odoo2
  odoo1:
    build: ./odoo
    tty: true
    volumes:
      - odoo-data:/var/lib/odoo
    ports:
      - 8069:8069
  odoo2:
    build: ./odoo
    tty: true
    volumes:
      - odoo-data:/var/lib/odoo
    ports:
      - 8070:8069

volumes:
  odoo-data:
  db-data:

